# si vas a mover este archivo recuerda actualizar la ruta del http-client.env.json en .gitignore

#categorias de productos
GET {{host}}/api/categories
Authorization: Bearer {{token}}

###

# listado de productos - con imagenes, formatos de imagen y paginacion.
GET {{host}}/api/products
    ?fields[0]=code
    &fields[1]=name
    &fields[2]=price
    &fields[3]=description
    &populate[images][fields][0]=url
    &populate[images][fields][1]=formats
    &pagination[pageSize]=100
    &publicationState=live
Authorization: Bearer {{token}}
Accept: application/json

###

#listado de productos entero.

GET {{host}}/api/products
    ?populate=*
    &pagination[pageSize]=100
    &publicationState=live
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{host}}/api/products?fields[0]=code&fields[1]=name&fields[2]=price&fields[3]=description&populate[images][fields][0]=url&populate[images][fields][1]=formats&pagination[pageSize]=100&publicationState=live
Authorization: Bearer {{token}}
Accept: application/json


###

# footer
GET {{host}}/api/footer
    ?fields[0]=id
    &fields[1]=documentId
    &populate[socials][fields][0]=kind
    &populate[socials][fields][1]=link
    &populate[footer_sections][fields][0]=title
    &populate[footer_sections][populate][links][fields][0]=label
    &populate[footer_sections][populate][links][fields][1]=link
    &populate[footer_sections][populate][links][fields][2]=external
Authorization: Bearer {{token}}
Accept: application/json


###
# about
GET http://localhost:1337/api/about-page?populate[background][fields][0]=url&populate=about_sections
Authorization: Bearer {{token}}
Accept: application/json