# si vas a mover este archivo recuerda actualizar la ruta del http-client.env.json en .gitignore

#categorias de productos
GET {{host}}/api/categories
Authorization: Bearer {{token}}

###

# listado de productos - con imagenes, formatos de imagen y paginacion.
GET {{host}}/api/products
    ?fields[0]=code
    &fields[1]=name
    &fields[2]=price
    &fields[3]=description
    &populate[images][fields][0]=url
    &populate[images][fields][1]=formats
    &pagination[pageSize]=100
    &publicationState=live
Authorization: Bearer {{token}}
Accept: application/json

###

#listado de productos entero.

GET {{host}}/api/products
    ?populate=*
    &pagination[pageSize]=100
    &publicationState=live
Authorization: Bearer {{token}}
Accept: application/json

###

# producto, optimizado
GET {{host}}/api/products
    ?fields[0]=code
    &fields[1]=name
    &fields[2]=price
    &fields[3]=description
    &populate[category][fields][0]=name
    &populate[images][sort][0]=id:asc
    &populate[images][populate]=*
    &pagination[pageSize]=100
    &publicationState=live
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{host}}/api/products
    ?fields[0]=code
    &fields[1]=name
    &fields[2]=price
    &fields[3]=description
    &populate[images][fields][0]=url
    &populate[images][fields][1]=formats
    &pagination[pageSize]=100
    &publicationState=live
Authorization: Bearer {{token}}
Accept: application/json


###

# footer
GET {{host}}/api/footer
    ?fields[0]=id
    &fields[1]=documentId
    &populate[socials][fields][0]=kindCategoryDTO
    &populate[socials][fields][1]=link
    &populate[footer_sections][fields][0]=title
    &populate[footer_sections][populate][links][fields][0]=label
    &populate[footer_sections][populate][links][fields][1]=link
    &populate[footer_sections][populate][links][fields][2]=external
Authorization: Bearer {{token}}
Accept: application/json

###
# about
GET {{host}}/api/about-page?populate=*
Authorization: Bearer {{token}}
Accept: application/json

###
# about completo
GET {{host}}/api/about-page
    ?fields[0]=header
    &populate[0]=background
    &populate[1]=about_sections.image
    &publicationState=live
Authorization: Bearer {{token}}
Accept: application/json


###
# terms and conditions
GET {{host}}/api/article-sections?filters[slug][$eq]=terms
Authorization: Bearer {{token}}
Accept: application/json

###
# brand
GET {{host}}/api/brand?populate=*
Authorization: Bearer {{token}}
Accept: application/json


###
GET {{host}}/api/categories
    ?fields[0]=documentId
    &fields[1]=name
    &fields[2]=description
    &populate[image][fields][0]=url
    &populate[image][fields][1]=formats
Authorization: Bearer {{token}}
Accept: application/json

###
#producto
GET {{host}}/api/product/tzczp7ofcyqu1mg4errdoa55?populate=*
Authorization: Bearer {{token}}
Accept: application/json