services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    command: pnpm --filter @pasteleria/web dev -- --port 3000
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:1337"
      NODE_ENV: "development"
    volumes:
      - ./web:/app/web
      - /app/web/.next
    ports:
      - "3000:3000"
    depends_on:
      - cms

  cms:
    build:
      context: .
      dockerfile: cms/Dockerfile
    command: pnpm --filter @pasteleria/cms dev
    environment:
      NODE_ENV: "development"
      HOST: "0.0.0.0"
      PORT: "1337"
      APP_KEYS: "dev1,dev2,dev3,dev4"
      API_TOKEN_SALT: "dev-salt"
      ADMIN_JWT_SECRET: "dev-admin"
      JWT_SECRET: "dev-jwt"
    volumes:
      - ./cms:/app
      - cms-data:/app/.tmp
      - cms-uploads:/app/public/uploads
    ports:
      - "1337:1337"

volumes:
  cms-data:
  cms-uploads:
