services:
  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    container_name: cms
    env_file:
      - ./cms/.env
    ports:
      - "1337:1337"
    volumes:
      # Montamos la carpeta .tmp completa (donde está data.db)
      - ./cms/.tmp:/opt/app/.tmp
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    env_file:
      - ./web/.env.production
    ports:
      - "3000:3000"
    volumes:
      - web_db:/app/web/prisma/database
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy --schema=/app/prisma/schema.prisma \
      && npx prisma db seed --schema=/app/prisma/schema.prisma \
      && node server.js"

volumes:
  web_db:
