version: '3.9'

services:
  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    container_name: cms
    env_file:
      - ./cms/.env
    ports:
      - "1337:1337"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: web
    env_file:
      - ./web/.env
    ports:
      - "3000:3000"
    volumes:
      - web_db:/app/web/prisma/database
    restart: unless-stopped
    depends_on:
      - cms
    # Ejecuta migraciones y seed al iniciar el contenedor
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && node web/server.js"

volumes:
  web_db:

